### ISSUE TITLE
Idea: would it be an option to prevent all emails via a setting?

### ISSUE THREAD

**Issue by seansan** [magmodules/magento1-channable-api#21]
Idea: would it be an option to prevent all emails? (separate issue because of different impact)

Now customers can receive any email via Magento like Orders (if enabled), Shipment (cannot disbled at the moment), Credit Memo (cannot disable) and FUE Follow Up Email

Would it be an idea to add a blackhole setting like [Block all emails to customer] yes/no

In many (maybe all) cases you want the Platform where the order is originating from (bol com) 
 to do the communication and not Magento.

![image](https://user-images.githubusercontent.com/652395/66567916-86ab2500-eb68-11e9-82cd-16d4793db590.png)

**Comment by Frank-Magmodules** [comment]
Hi @seansan,
Thank you for sharing your idea.
The module only imports the orders. We suggest you to import the orders from the marketplace in a unique store view, so you can disable sending credit memo, follow up emails, etc using the built in Magento settings. 

We added above settings as these can be disabled directly on import. To block all customer emails after import is not a simple edit and would require a lot of function rewrites / observers. 
Aside from the question if this is possible, Magento 1 is reaching EOL, so we will not add a feature of this extend  to the module at this stage.
