### ISSUE TITLE
Order received in wrong Currency

### ISSUE THREAD

**Issue by webita** [magmodules/magento1-channable-api#22]
Hi, we are using the connector to download orders from Channable, but when we receive orders in a currency other than the default one (in our case EUR) unfortunately these are not correctly converted. The result is that for example we have on Magento 1 a Swedish SEK not converted into EUR with consequent problems for the management and calculation of income and expenses. Can this problem be solved? I have been talking for several weeks with the Channable team and now I have seen that for the version of the connector you have developed for Magento 2 to an equal problem, you have released an update, but for this version for Magento 1 no. Can you release an updated version by any chance? Thanks

**Comment by Frank-Magmodules** [comment]
Hi @webita, thank you for opening this issue. We have placed this on the backlog to create a fix for this. Will be released somewhere in the next couple of weeks

**Comment by webita** [comment]
Thank you very much, now we attend the new release/version of the extension.

**Comment by webita** [comment]
Hi, any news about the update? We look forward to it, you don't know how much I need it

**Comment by Marvin-Magmodules** [comment]
Hi @webita,
We are happy to share that we've just released the new [1.4.1](https://github.com/magmodules/magento1-channable-api/releases/tag/v1.4.1) version with a fix for this issue. Thank you for the detailed report and patience. We are closing this issue now but please feel free to reopen the issue if this still occurs.
