### ISSUE TITLE
Add composer.json to allow installation with composer

### ISSUE THREAD

**Issue by Swahjak** [magmodules/magento1-channable-api#4]
Currently I have to maintain my own repository to allow installation with https://github.com/Cotya/magento-composer-installer. It would be great if a composer.json could be included so we can include it with composer directly from the source.

This also goes for the other magento1 modules, in our case:
* https://github.com/Magmodules/magento1-channable
* https://github.com/Magmodules/magento1-kiyoh

**Comment by magmodules** [comment]
Done
